stages:
  download:
    cmd: python raw_data/make_dataset.py --config=config/params.yaml
    deps: 
      - raw_data/make_dataset.py
      - config/params.yaml
    outs:
      - raw_data/raw_data.csv
  # training:
  #   cmd: python src/models/train_model.py
  #   deps:
  #     - src/models/train_model.py
  #     - params.yaml
  #   params:
  #     - estimators.SVM.params.random_state
  #     # - passes
  #   # outs:
  #   #   - saved_models/best_model.joblib
  # prediction:
  #   cmd: python src/models/predict_model.py
  #   deps:
  #     - src/models/predict_model.py
    # params:
    #   - threshold
    #   - passes
    # outs:
    #   - reports/scores.json