stages:
  download:
    cmd: python raw_data/make_dataset.py --config=config/params.yaml
    deps:
      - raw_data/make_dataset.py
      - config/params.yaml
    outs:
      - raw_data/raw_data.csv

  split_data:
    cmd: python src/data_manager.py --config=config/params.yaml
    deps:
      - src/data_manager.py
      - config/params.yaml
    outs:
      - processed_data/x_train.csv
      - processed_data/y_train.csv
      - processed_data/x_test.csv
      - processed_data/y_test.csv
  training:
    cmd: python src/train_pipeline.py --config=config/params.yaml
    deps:
      - src/train_pipeline.py
      - config/params.yaml
    outs:
      - saved_models/best_model_v1.joblib
  # prediction:
  #   cmd: python src/models/predict_model.py
  #   deps:
  #     - src/models/predict_model.py
    # params:
    #   - threshold
    #   - passes
    # outs:
    #   - reports/scores.json
