name: Makefile CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: make requirements
      
    - name: pre nuild test
      run: make pre_build
      
#     - name: Run check
#       run: make check
      
#     - name: Run distcheck
#       run: make distcheck
